image: "python:3.7.3"

stages:
    - test
    - deploy

test job:
    stage: test
    script:
      - apt-get update -qy
      - apt-get install -y python3-dev python3-pip python3-venv
      - python3 -m venv venv
      - source ./venv/bin/activate
      - pip3 install -r ./requirements/requirements.txt
      - python -m unittest discover -s ./tests/unittests

deploy job:
    stage: deploy
    script:
      - echo 'You are deploying now'