stages:
    - build
    - deploy

build job:
    stage: build
    script:
      - export PYTHONPATH=.
      - apt-get update -qy
      - apt-get install -y python3-dev python3-pip
      - pip3 install -r ./requirements/requirements.txt
      - python -m unittest discover -s ./tests/unittests

deploy job:
    stage: deploy
    script:
      - apt-get update -qy
      - apt-get install curl -y