"""empty message

Revision ID: 6d826d079d4d
Revises: a6fa3bd16b6c
Create Date: 2019-10-31 18:24:13.431344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d826d079d4d'
down_revision = 'a6fa3bd16b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trip', ['trip_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='unique')
    # ### end Alembic commands ###
