"""empty message

Revision ID: 7c71bc2aee0e
Revises: 9b9c3e9269b8
Create Date: 2019-10-31 16:34:19.031350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c71bc2aee0e'
down_revision = '9b9c3e9269b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip-user',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.trip_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'user_id')
    )
    op.add_column('trip', sa.Column('trip_uuid', sa.String(length=36), nullable=True))
    op.drop_column('trip', 'trip_uid')
    op.create_unique_constraint(None, 'user_profile', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.add_column('trip', sa.Column('trip_uid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_column('trip', 'trip_uuid')
    op.drop_table('trip-user')
    # ### end Alembic commands ###
